/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpaIdRouteImport } from './routes/upa.$id'

const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpaIdRoute = UpaIdRouteImport.update({
  id: '/upa/$id',
  path: '/upa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/buscar': typeof BuscarRoute
  '/eventos': typeof EventosRoute
  '/upa/$id': typeof UpaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/buscar': typeof BuscarRoute
  '/eventos': typeof EventosRoute
  '/upa/$id': typeof UpaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/buscar': typeof BuscarRoute
  '/eventos': typeof EventosRoute
  '/upa/$id': typeof UpaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/avaliar' | '/buscar' | '/eventos' | '/upa/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/avaliar' | '/buscar' | '/eventos' | '/upa/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliar'
    | '/buscar'
    | '/eventos'
    | '/upa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvaliarRoute: typeof AvaliarRoute
  BuscarRoute: typeof BuscarRoute
  EventosRoute: typeof EventosRoute
  UpaIdRoute: typeof UpaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upa/$id': {
      id: '/upa/$id'
      path: '/upa/$id'
      fullPath: '/upa/$id'
      preLoaderRoute: typeof UpaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvaliarRoute: AvaliarRoute,
  BuscarRoute: BuscarRoute,
  EventosRoute: EventosRoute,
  UpaIdRoute: UpaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
